- name: "Install AUR helper and packages"
  hosts:      localhost
  connection: local

  tasks:

  - name: Create build user
    user:
      name:        aur_builder
      group:       wheel
      create_home: no
      home:        /tmp

  - name: Install build tools
    package:
      name:         '{{ item }}'
      state:        present
      update_cache: True
    with_items:
      - base-devel

  - name: "Gather package facts"
    package_facts:
      manager: "auto"

  - name: Install PIKAUR
    when: "'pikaur' not in ansible_facts['packages']"
    become: yes
    become_user: aur_builder
    script: ./lib/installFromAur.sh pikaur

  - name: Install ansible-aur-git
    when: "'ansible-aur-git' not in ansible_facts['packages']"
    become: yes
    become_user: aur_builder
    script: ./lib/installFromAur.sh ansible-aur-git

  - name: Install AUR packages
    become: yes
    become_user: aur_builder
    aur:
      name: '{{ item }}'
    with_items:
      - free42
      - insync
      - c-lolcat
      - python-i3-py
      - ttf-unifont
      - ttf-symbola





